// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';

export interface IBlogPostFields {
  /** Title */
  title: string;

  /** Image */
  image?: Asset | undefined;

  /** post */
  post: string;
}

/** A blog post */

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'blogPost';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IContactDetailsFields {
  /** Label */
  label: string;

  /** Value */
  value: string;

  /** href */
  href?: string | undefined;
}

/** A single entry for the contact detaiils */

export interface IContactDetails extends Entry<IContactDetailsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'contactDetails';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IContentDetailsFields {
  /** Title */
  title: string;

  /** Contact Details */
  contactDetails?: IContactDetails[] | undefined;
}

/** A collection of contact details */

export interface IContentDetails extends Entry<IContentDetailsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'contentDetails';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ICvFields {
  /** Title */
  title: string;

  /** Content */
  content: (IContentDetails | ISection | ISkills | IWorkHistory)[];
}

/** Curriculum Vitae */

export interface ICv extends Entry<ICvFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'cv';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IExternalLinkFields {
  /** Text */
  text: string;

  /** Url */
  url: string;
}

/** Link to a page not on this site */

export interface IExternalLink extends Entry<IExternalLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'externalLink';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IFreeTextFields {
  /** Text */
  text: string;
}

/** A block of text, write what you want */

export interface IFreeText extends Entry<IFreeTextFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'freeText';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IGenericPageFields {
  /** Title */
  title: string;

  /** Content */
  content: (ICv | IFreeText | INavBar | ISection)[];
}

/** A generic page */

export interface IGenericPage extends Entry<IGenericPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'genericPage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IImageFields {
  /** Description */
  description: string;

  /** Image */
  image: Asset;
}

export interface IImage extends Entry<IImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'image';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILinkFields {
  /** Text */
  text: string;

  /** Link */
  link: IPage;
}

/** A link to a page on the site */

export interface ILink extends Entry<ILinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'link';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface INavBarFields {
  /** Links */
  links: (IExternalLink | ILink)[];
}

/** A collection of navigable elements */

export interface INavBar extends Entry<INavBarFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'navBar';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IPageFields {
  /** path */
  path: string;

  /** Content */
  content: IBlogPost | ICv | IGenericPage;
}

/** A location on the website that links to some content */

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'page';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IRedirectFields {
  /** to */
  to: IPage;

  /** Label */
  label?: string | undefined;
}

export interface IRedirect extends Entry<IRedirectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'redirect';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IRoleDescriptionFields {
  /** Buisness Name */
  buisnessName: string;

  /** Job Title */
  jobTitle: string;

  /** Start Date */
  startDate: string;

  /** endDate */
  endDate?: string | undefined;

  /** Description */
  description: string;
}

/** Summary of a role */

export interface IRoleDescription extends Entry<IRoleDescriptionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'roleDescription';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISectionFields {
  /** Title */
  title: string;

  /** Content */
  content: (IFreeText | IImage | IRoleDescription | ISkills)[];
}

/** A titled section of content */

export interface ISection extends Entry<ISectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'section';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISkillListFields {
  /** Title */
  title: string;

  /** Skills */
  skills: string[];
}

/** A list of skills */

export interface ISkillList extends Entry<ISkillListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'skillList';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISkillsFields {
  /** Section Title */
  groupTitle: string;

  /** Description */
  description?: string | undefined;

  /** Skills Lists */
  skillsLists: ISkillList[];
}

/** A list of lists of skills */

export interface ISkills extends Entry<ISkillsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'skills';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IWorkHistoryFields {
  /** Title */
  title: string;

  /** Roles */
  roles: IRoleDescription[];
}

/** History of roles */

export interface IWorkHistory extends Entry<IWorkHistoryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'workHistory';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'blogPost'
  | 'contactDetails'
  | 'contentDetails'
  | 'cv'
  | 'externalLink'
  | 'freeText'
  | 'genericPage'
  | 'image'
  | 'link'
  | 'navBar'
  | 'page'
  | 'redirect'
  | 'roleDescription'
  | 'section'
  | 'skillList'
  | 'skills'
  | 'workHistory';

export type LOCALE_CODE = 'en-GB' | 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
