name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 2025

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Gisleburts Dioxus Deploy"
        uses: Gisleburt/dioxus-deploy-action@0.1.3-cname-nojekyl
        with:
          outDirectory: "target/dx/gisleburt-github-io/release/web/public"
          cname: danielmason.com